#! /bin/sh

# Environment Variables
XDG_CONFIG_HOME=$HOME

function set_Keybindings()
{
        #
        # Set Keybinding for BSPWM via SXHKD
        #
	sxhkd -c $HOME/.config/sxhkd/sxhkdrc |& tee -a ~/.logs/sxhkd.log &
}

autostart()
{
    # Local Variables
    path_config_Picom=~/.config/picom/picom.conf

	# --- Settings & Initialization
    # Start Keybinding
    pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
	set_Keybindings

    # Start Compositor
    picom --config $path_config_Picom &
}


# --- Autostart
# pgrep -x sxhkd > /dev/null || sxhkd &
autostart

# --- BSPWM Parameters

# Monitor Params
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d	01 02 03 04 05 06 07 08 09 10	# Monitor Window names

### Border Config Params - Global Settings ###
bspc config pointer_action1 move 			# Right Click; Move Window
bspc config pointer_action2 resize_side 	# Right Click; Resize window vertically/horizontally
bspc config pointer_action3 resize_corner 	# Right Click; Resize window diagonally

### Border Config Params - Monitor & Desktop settings ###
bspc config border_width         2			# Window border width (How thick)
bspc config window_gap           6 			# Default window_gap: 12

### Border Config Params - Windows ###
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Border Config Params - Color ###
bspc config normal_border_color	 "#4c566a"
bspc config active_border_color	 "#1e1e1e"
bspc config focused_border_color "#327bd1"

# Program Rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a urxvt state=floating
